apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sp-front
  labels:
    appLabel: sp-front
spec:
  replicas: 2
  selector:
    matchLabels:
      appLabel: sp-front
  template:
    metadata:
      labels:
        appLabel: sp-front
    spec:
      containers:
        - name: sp-front
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0
---
apiVersion: v1
kind: Pod
metadata:
  name: sp-queue
  labels:
    appLabel: sp-queue
spec:
  containers:
    - name: sp-queue
      image: richardchesterwood/k8s-fleetman-queue:release1
