apiVersion: v1
kind: Service
metadata:
  name: sp-front
spec:
  type: NodePort
  selector:
    appLabel: sp-front
  ports:
  - port: 80
    name: http
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: sp-queue
spec:
  type: NodePort
  selector:
    appLabel: sp-queue
  ports:
    - port: 8161
      name: http
      nodePort: 30010
